-- https://programmers.co.kr/learn/courses/30/lessons/59413

SELECT 
    HOURS.HOUR
    , IFNULL(COUNTS.COUNT, 0) AS COUNT
FROM 
    (SELECT 0 AS HOUR UNION 
    SELECT 1 AS HOUR UNION 
    SELECT 2 AS HOUR UNION 
    SELECT 3 AS HOUR UNION 
    SELECT 4 AS HOUR UNION 
    SELECT 5 AS HOUR UNION 
    SELECT 6 AS HOUR UNION 
    SELECT 7 AS HOUR UNION 
    SELECT 8 AS HOUR UNION 
    SELECT 9 AS HOUR UNION 
    SELECT 10 AS HOUR UNION 
    SELECT 11 AS HOUR UNION 
    SELECT 12 AS HOUR UNION 
    SELECT 13 AS HOUR UNION 
    SELECT 14 AS HOUR UNION 
    SELECT 15 AS HOUR UNION 
    SELECT 16 AS HOUR UNION 
    SELECT 17 AS HOUR UNION 
    SELECT 18 AS HOUR UNION 
    SELECT 19 AS HOUR UNION 
    SELECT 20 AS HOUR UNION 
    SELECT 21 AS HOUR UNION 
    SELECT 22 AS HOUR UNION 
    SELECT 23 AS HOUR) AS HOURS
    LEFT JOIN 
        (SELECT 
            HOUR(DATETIME) AS HOUR
            , COUNT(*) AS COUNT
        FROM 
            ANIMAL_OUTS 
        GROUP BY 
            HOUR) AS COUNTS
        ON HOURS.HOUR = COUNTS.HOUR
ORDER BY 
    HOURS.HOUR
